"""create pairing_codes table

Revision ID: 6be18ec970b6
Revises: 78117a725b26
Create Date: 2026-09-05 15:27:38.102850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be18ec970b6'
down_revision: Union[str, Sequence[str], None] = '78117a725b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairing_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pairing_codes')
    # ### end Alembic commands ###
